### ISSUE TITLE
ModuleNotFoundError: GNATS_Python_Header_standalone

### ISSUE THREAD

**Issue by edecarlo-swri** [OptimalSynthesisInc/GNATS#4]
The `GNATS_Python_Header_standalone` file is not packaged with the Beta 1.10 release and so the sample files cannot be executed.

**Comment by edecarlo-swri** [comment]
This is specifically with the Standalone version. I see it is with the Client version, and I will get it from there in the meantime.

**Comment by OptimalSynthesisInc** [comment]
Oliver says he has fixed this. Please check if it works now. Thanks,
PK Menon
OSI
